apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ebankNamespace
type: Opaque
data:
  secret: TVRRMU1EUTJaR0prT0dSak5qRTVZemszTURNNE1EY3lZVGhtWkRZd05URTNOREV4WkRZNVlqQmlOalkyWkdJellqUm1PR1k1WkRrNE1XTXdNemcyT1RReU5EWTNPRFpsWkdWa01EZGtaakl5WVRRM1pqSmpZMlE0TVdZeE9Ua3lOalZpWlE9PQ==
