apiVersion: v1
kind: Service
metadata:
  name: orderapi
  namespace: ebankNamespace
  labels:
    app: orderapi
spec:
  selector:
    app: orderapi
  ports:
    - name: http
      port: 80
      targetPort: 8082
