apiVersion: v1
kind: Service
metadata:
  name: ordersystemfrontend
  namespace: ebankNamespace
  labels:
    app: ordersystemfrontend
spec:
  selector:
    app: ordersystemfrontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
