commonLabels:
  app.kubernetes.io/genereted-by: Tom

namespace: ebankNamespace

resources:
  - namespace.yml
  # Individual apps
  - addressapi-k8s/addressapi-deployment.yml
  - addressapi-k8s/addressapi-service.yml
  - addressapi-k8s/addressapi-mongodb.yml
  - addressapi-k8s/addressapi-elasticsearch.yml
  - addressapi-k8s/jwt-secret.yml
  - addressapi-k8s/addressapi-prometheus-sm.yml
  - orderapi-k8s/orderapi-deployment.yml
  - orderapi-k8s/orderapi-service.yml
  - orderapi-k8s/orderapi-mongodb.yml
  - orderapi-k8s/orderapi-elasticsearch.yml
  - orderapi-k8s/jwt-secret.yml
  - orderapi-k8s/orderapi-prometheus-sm.yml
  - ordersystemfrontend-k8s/ordersystemfrontend-deployment.yml
  - ordersystemfrontend-k8s/ordersystemfrontend-service.yml
  - ordersystemfrontend-k8s/ordersystemfrontend-mongodb.yml
  - ordersystemfrontend-k8s/ordersystemfrontend-elasticsearch.yml
  - ordersystemfrontend-k8s/jwt-secret.yml
  - ordersystemfrontend-k8s/ordersystemfrontend-prometheus-sm.yml
  - productapi-k8s/productapi-deployment.yml
  - productapi-k8s/productapi-service.yml
  - productapi-k8s/productapi-postgresql.yml
  - productapi-k8s/productapi-elasticsearch.yml
  - productapi-k8s/jwt-secret.yml
  - productapi-k8s/productapi-prometheus-sm.yml
  - statusapi-k8s/statusapi-deployment.yml
  - statusapi-k8s/statusapi-service.yml
  - statusapi-k8s/statusapi-mongodb.yml
  - statusapi-k8s/statusapi-elasticsearch.yml
  - statusapi-k8s/jwt-secret.yml
  - statusapi-k8s/statusapi-prometheus-sm.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
# service discovery eureka/consul

patchesJson6902:
