apiVersion: v1
kind: Service
metadata:
  name: productapi
  namespace: ebankNamespace
  labels:
    app: productapi
spec:
  selector:
    app: productapi
  ports:
    - name: http
      port: 80
      targetPort: 8083
