apiVersion: v1
kind: Secret
metadata:
  name: productapi-postgresql
  namespace: ebankNamespace
  labels:
    app: productapi-postgresql
type: Opaque
data:
  postgresql-password: MTNiOTMwMDc0NzViMWM4NmI5NzU2Mzc0OTNmODE3NjM2MzY5ODllNDY5NmY5MDUwMjlmZTIxNDg1NzQ4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-postgresql
  namespace: ebankNamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi-postgresql
  template:
    metadata:
      labels:
        app: productapi-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:13.2
          env:
            - name: POSTGRES_USER
              value: productapi
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: productapi-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-postgresql
  namespace: ebankNamespace
spec:
  selector:
    app: productapi-postgresql
  ports:
    - port: 5432
