apiVersion: v1
kind: Service
metadata:
  name: statusapi
  namespace: ebankNamespace
  labels:
    app: statusapi
spec:
  selector:
    app: statusapi
  ports:
    - name: http
      port: 80
      targetPort: 8084
